DROP TABLE if exists artist; 

CREATE TABLE artist( 
    name TEXT NOT NULL
); 

INSERT INTO artist VALUES ('DRAKE'); 
INSERT INTO artist VALUES ('JUSTIN BIEBER'); 
INSERT INTO artist VALUES ('GIVEON'); 
INSERT INTO artist VALUES ('OLIVIA RODRIGO'); 
INSERT INTO artist VALUES ('TAYLOR SWIFT'); 


DROP TABLE if exists albums;

CREATE TABLE albums( 
    album TEXT NOT NULL,
    artist TEXT NOT NULL
); 

INSERT INTO albums VALUES ('CERTIFIED LOVER BOY', 'DRAKE');
INSERT INTO albums VALUES ('JUSTICE', 'JUSTIN BIEBER'); 
INSERT INTO albums VALUES ('TAKE TIME', 'GIVEON'); 
INSERT INTO albums VALUES ('SOUR', 'OLIVIA RODRIGO'); 
INSERT INTO albums VALUES ('RED', 'TAYLOR SWIFT');  

DROP TABLE if exists songs; 

CREATE TABLE songs( 
    song TEXT NOT NULL, 
    album1 TEXT NOT NULL, 
    track INT NOT NULL, 
    play time INT NOT NULL
);

INSERT INTO songs VALUES ('NO FRIENDS IN THE INDUSTRY', 'CERTIFIED LOVER BOY', 12, 204); 
INSERT INTO songs VALUES ('2 MUCH', 'JUSTICE', 1, 152); 
INSERT INTO songs VALUES ('HEART BREAK ANNIVERSARY', 'TAKE TIME', 6, 198); 
INSERT INTO songs VALUES ('DRIVERS LICENSE', 'SOUR', 3, 241); 
INSERT INTO songs VALUES ('ALL TOO WELL', 'RED', 5, 329); 

SELECT * FROM artist; 
SELECT * FROM albums; 
SELECT * FROM songs;

